// danmaku-components/src/vue/DanmakuRenderer.vue
<template>
  <div
    ref="danmakuContainer"
    class="danmaku-container"
    :style="{...containerStyle}"
  ></div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch, computed } from 'vue'
import type { CSSProperties } from 'vue'
import { DanmakuCoreRenderer } from '../core/DanmakuCoreRenderer'
import type { Danmaku, DanmakuConfig } from '../types'

// Props
const props = defineProps<{
  config?: DanmakuConfig
  danmaku?: Danmaku | null
}>()

// Emits
const emit = defineEmits<{
  pause: []
  resume: []
  danmakuEnd: [danmaku: Danmaku]
  danmakuClick: [danmaku: Danmaku]
  containerClick: []
}>()

// Refs
const danmakuContainer = ref<HTMLElement>()
const renderer = ref<DanmakuCoreRenderer | null>(null)

// 容器样式对象
const containerStyle = computed(() => {
  const style: CSSProperties = {}
  if (props.config?.containerWidth) {
    style.width = `${props.config.containerWidth}px`
  }
  if (props.config?.containerHeight) {
    style.height = `${props.config.containerHeight}px`
  }
  return style
})

// 监听弹幕数据变化
watch(() => props.danmaku, (newDanmaku) => {
  if (newDanmaku && renderer.value) {
    renderer.value.render(newDanmaku)
  }
})

// 监听配置变化
watch(() => props.config, () => {
  if (renderer.value && danmakuContainer.value) {
    // 重新初始化渲染器
    renderer.value.destroy()
    initRenderer()
  }
}, { deep: true })

// 初始化渲染器
function initRenderer() {
  if (!danmakuContainer.value) return
  
  // 创建核心渲染器实例
  renderer.value = new DanmakuCoreRenderer()
  
  // 配置回调函数
  const configWithCallbacks: DanmakuConfig = {
    ...props.config,
    onPause: () => emit('pause'),
    onResume: () => emit('resume'),
    onDanmakuEnd: (danmaku) => emit('danmakuEnd', danmaku),
    onDanmakuClick: (danmaku) => emit('danmakuClick', danmaku),
    onContainerClick: () => emit('containerClick')
  }
  
  // 初始化渲染器
  renderer.value.init(danmakuContainer.value, configWithCallbacks)
}

// 组件方法
const pause = () => {
  renderer.value?.pause()
}

const resume = () => {
  renderer.value?.resume()
}

const clear = () => {
  renderer.value?.clear()
}

const updateSize = (width: number, height: number) => {
  renderer.value?.updateSize(width, height)
}

// 暴露方法给父组件
defineExpose({
  pause,
  resume,
  clear,
  updateSize
})

// 生命周期
onMounted(() => {
  initRenderer()
})

onUnmounted(() => {
  if (renderer.value) {
    renderer.value.destroy()
    renderer.value = null
  }
})
</script>

<style scoped>
.danmaku-container {
  position: relative;
  overflow: hidden;
  pointer-events: auto;
}

/* 弹幕样式变量 */
:deep(.danmaku-item) {
  font-weight: bold;
  white-space: nowrap;
  overflow: visible;
  animation-fill-mode: forwards;
  pointer-events: all;
  user-select: none;
  z-index: 1000;
}

/* 滚动弹幕 */
:deep(.danmaku-scroll) {
  background: rgba(0, 0, 0, 0.5);
  color: white;
  padding: 2px 10px;
  border-radius: 4px;
}

/* 顶部弹幕 */
:deep(.danmaku-top) {
  background: rgba(0, 0, 0, 0.5);
  color: white;
  padding: 2px 10px;
  border-radius: 4px;
}

/* 底部弹幕 */
:deep(.danmaku-bottom) {
  background: rgba(0, 0, 0, 0.5);
  color: white;
  padding: 2px 10px;
  border-radius: 4px;
}

/* 表情弹幕 */
:deep(.danmaku-emoji) {
  background: transparent;
}

/* 反向弹幕 */
:deep(.danmaku-reverse) {
  background: rgba(0, 0, 0, 0.5);
  color: white;
  padding: 2px 10px;
  border-radius: 4px;
}

/* 管理员标记 */
:deep(.admin-badge) {
  display: inline-block;
  background-color: #ff0000;
  color: #fff;
  font-size: 12px;
  padding: 0 5px;
  border-radius: 3px;
  margin-right: 5px;
  line-height: 18px;
}
</style>

// danmaku-components/src/react/DanmakuRenderer.tsx
import React, { useRef, useEffect, forwardRef, useImperativeHandle } from 'react'
import { DanmakuCoreRenderer } from '../core/DanmakuCoreRenderer'
import type { DanmakuConfig } from '../types'
import type { DanmakuComponentRef, DanmakuRendererProps } from '../types/public'

const DanmakuRenderer = forwardRef<DanmakuComponentRef, DanmakuRendererProps>((props, ref) => {
  const { 
    config, 
    danmaku, 
    onPause, 
    onResume, 
    onDanmakuEnd, 
    onDanmakuClick,
    onContainerClick 
  } = props
  
  const containerRef = useRef<HTMLDivElement>(null)
  const rendererRef = useRef<DanmakuCoreRenderer | null>(null)
  
  // 初始化渲染器
  useEffect(() => {
    if (!containerRef.current) return
    
    // 创建渲染器实例
    const renderer = new DanmakuCoreRenderer()
    
    // 配置回调
    const configWithCallbacks: DanmakuConfig = {
      ...config,
      onPause,
      onResume,
      onDanmakuEnd,
      onDanmakuClick,
      onContainerClick
    }
    
    // 初始化
    renderer.init(containerRef.current, configWithCallbacks)
    rendererRef.current = renderer
    
    // 清理
    return () => {
      renderer.destroy()
      rendererRef.current = null
    }
  }, []) // 仅在挂载时初始化
  
  // 监听配置变化
  useEffect(() => {
    if (rendererRef.current && config) {
      // 重新初始化以应用新配置
      rendererRef.current.destroy()
      const configWithCallbacks: DanmakuConfig = {
        ...config,
        onPause,
        onResume,
        onDanmakuEnd,
        onDanmakuClick,
        onContainerClick
      }
      rendererRef.current.init(containerRef.current!, configWithCallbacks)
    }
  }, [config]) // 监听配置变化
  
  // 监听弹幕数据
  useEffect(() => {
    if (danmaku && rendererRef.current) {
      rendererRef.current.render(danmaku)
    }
  }, [danmaku])
  
  // 暴露方法给父组件
  useImperativeHandle(ref, () => ({
    pause: () => rendererRef.current?.pause(),
    resume: () => rendererRef.current?.resume(),
    clear: () => rendererRef.current?.clear(),
    updateSize: (width: number, height: number) => rendererRef.current?.updateSize(width, height)
  }))
  
  // 计算容器样式
  const containerStyle: React.CSSProperties = {
    position: config?.fullScreen ? 'fixed' : 'relative',
    top: config?.fullScreen ? 0 : 'auto',
    left: config?.fullScreen ? 0 : 'auto',
    right: config?.fullScreen ? 0 : 'auto',
    bottom: config?.fullScreen ? 0 : 'auto',
    width: config?.containerWidth ? `${config.containerWidth}px` : '100%',
    height: config?.containerHeight ? `${config.containerHeight}px` : '100%',
    overflow: 'hidden',
    pointerEvents: config?.enableClickPause ? 'auto' : 'none',
    zIndex: 10,
    backgroundColor: 'transparent'
  }
  
  return (
    <div
      ref={containerRef}
      className="danmaku-container"
      style={containerStyle}
    />
  )
})

// 添加默认样式
const style = document.createElement('style')
style.textContent = `
  .danmaku-item {
    font-weight: bold;
    white-space: nowrap;
    overflow: visible;
    animation-fill-mode: forwards;
    pointer-events: all;
    user-select: none;
    z-index: 1000;
  }
  
  .danmaku-scroll {
    background: rgba(0, 0, 0, 0.5);
    color: white;
    padding: 2px 10px;
    border-radius: 4px;
  }
  
  .danmaku-top {
    background: rgba(0, 0, 0, 0.5);
    color: white;
    padding: 2px 10px;
    border-radius: 4px;
  }
  
  .danmaku-bottom {
    background: rgba(0, 0, 0, 0.5);
    color: white;
    padding: 2px 10px;
    border-radius: 4px;
  }
  
  .danmaku-emoji {
    background: transparent;
  }
  
  .danmaku-reverse {
    background: rgba(0, 0, 0, 0.5);
    color: white;
    padding: 2px 10px;
    border-radius: 4px;
  }
  
  .admin-badge {
    display: inline-block;
    background-color: #ff0000;
    color: #fff;
    font-size: 12px;
    padding: 0 5px;
    border-radius: 3px;
    margin-right: 5px;
    line-height: 18px;
  }
`
document.head.appendChild(style)

export default DanmakuRenderer
